name: CI/CD for Flask App

on:
  push:
    branches: [ "main", "master", "feature/flask-app" ]
  pull_request:
    branches: [ "main", "master", "feature/flask-app" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 FlaskWebProject1 --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run tests
        run: |
          pip install pytest
          pytest FlaskWebProject1/tests

      - name: Build Docker image
        run: |
          docker build -t flask-app .
